services:
  # pakturaly:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=80
  #   depends_on:
  #     - keycloak
  #   networks:
  #     - app-network
 
  #docker run -p 127.0.0.1:8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:26.5.1 start-dev

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    # depends_on:
    #   - postgres
    # networks:
    #   - app-network

  # postgres:
  #   image: postgres:17.4
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data_keycloak:/var/lib/postgresql/data
  #   networks:
  #     - app-network
 
# volumes:
#   postgres_data_keycloak: 
  
# networks:
#   app-network:
#     driver: bridge  
